// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUeoG6HxCzdfKdLrzhSDDX3Hyi-RKtRHY',
    appId: '1:44528543910:web:b69f0d77863a35213a6c67',
    messagingSenderId: '44528543910',
    projectId: 'chat-app-8122b',
    authDomain: 'chat-app-8122b.firebaseapp.com',
    storageBucket: 'chat-app-8122b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjaqbxbtn-XTvzw18JvT4NDOM1VOxRewY',
    appId: '1:44528543910:android:d3f5763ab37311b73a6c67',
    messagingSenderId: '44528543910',
    projectId: 'chat-app-8122b',
    storageBucket: 'chat-app-8122b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZOfwXW4s6g-GM-vfQ9WgQHuJdx-p2XHo',
    appId: '1:44528543910:ios:d7c2daa40db336453a6c67',
    messagingSenderId: '44528543910',
    projectId: 'chat-app-8122b',
    storageBucket: 'chat-app-8122b.appspot.com',
    iosBundleId: 'com.example.flutterAppChat',
  );
}
